services:
  back:
    build:
      context: ./back
    container_name: task-back
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=sqlite:////app/var/data.db
    volumes:
      - ./back/var:/app/var
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  default:
    name: task-network

